PATH(BOWER,/bower_components)
PATH(CSS,/css)

/------------------------------------------------------------------------------/
/ Imported                                                                     /
/------------------------------------------------------------------------------/
INCLUDE(BOWER/bootstrap/dist/css/bootstrap.css)
INCLUDE(BOWER/ngDialog/css/ngDialog.css)
INCLUDE(BOWER/ngDialog/css/ngDialog-theme-default.css)


/------------------------------------------------------------------------------/
/ My styles                                                                    /
/------------------------------------------------------------------------------/
INCLUDE(CSS/angular-wizard.css)
INCLUDE(CSS/ng-ration.css)
