PATH(BOWER,/bower_components)
PATH(CSS,/css)

/------------------------------------------------------------------------------/
/ Imported                                                                     /
/------------------------------------------------------------------------------/
//INCLUDE(BOWER/closurelibrary/closure/css/inlay/g-base.css)
//INCLUDE(BOWER/closurelibrary/closure/goog/css/dialog.css)
INCLUDE(BOWER/bootstrap/dist/css/bootstrap.css)
INCLUDE(BOWER/ng-slider-menu/src/css/slide-menu.css)

/------------------------------------------------------------------------------/
/ My styles                                                                    /
/------------------------------------------------------------------------------/
INCLUDE(CSS/angular-wizard.css)
INCLUDE(CSS/ng-ration.css)
