BIN = bin
PHP = php
JAVA=java
JAVA_OPT=-Xmx128m -XX:+UseConcMarkSweepGC
JAR=$(JAVA) $(JAVA_OPT) -jar
PLOVR=$(JAR) bin/plovr.jar
COMPRESS=gzip -k -f
CSSCOMP = $(JAR) $(BIN)/yuicompressor-2.4.8.jar --type css -o
LESS = lessc -x
COMP = $(M4) resource-list/resource-list.m4
M4 = $(call firstavailable,gm4,m4) -P
JS = js
EMPTY =
SPACE = $(EMPTY) $(EMPTY)
COMMA = ,

firstavailable = $(firstword $(shell which $1 $2 $3 $4 $5 false))
resources = $(subst $(SPACE),$3,$(addprefix $2,$(strip $(shell $(COMP) $1))))
webroot = $(call resources,$1,,$(COMMA))
fsroot = $(call resources,$1,.,$(SPACE))

CSSS := $(call fsroot,css/css.resource)
JSS := $(call fsroot,$(JS)/javascript.resource)


%.css: %.less
	$(LESS) $< > $@

%.css.gz: %.css
	$(COMPRESS) $<


build: index.html css js


js: $(JS)/products.js

$(JS)/products.js: etc/products/*.csv $(BIN)/compile-product-list.php
	$(PHP) $(BIN)/compile-product-list.php etc/products/*.csv > $@

index.html: $(JS)/javascript.resource css/css.resource partials/application.html
	$(M4) $(if $(NODEBUG),,-D ALLOWDEBUG=1) -D JAVASCRIPTS="$(call webroot,$<)" -D STYLES="$(call webroot,css/css.resource,)" etc/m4/*.m4 partials/application.html > $@


css: css/ng-ration.css css/angular-wizard.css


validate:
	jshint $(filter-out js/locale/angular-locale_ru-ru.js, $(shell find js -name '*.js'))


upload: build css/combined.css.gz


css/combined.css: $(CSSS)
	cat $(CSSS) | $(CSSCOMP) $@


$(COMPILED_JS): compiled-js-config js $(JS_FILES)
	$(AUTOGENERATED) > $@
	$(PLOVR) build $< >> $@


.INTERMEDIATE: compiled-js-config
compiled-js-config: $(PLOVRCONF)/plovr.m4 $(JS)/javascript.Manifest $(JS_FILES)
	$(M4) -D INPUTS="$(JSS)" -D PRETTY=$(if $(DEBUG),true,false) $(M4LANG) $< > $@
	$(call test_file_not_blank,$@)


.PHONY: product-id
product-id:
	for i in `seq 1 1000`; do echo -n ',,,,' >> etc/products/$(NAME).csv; uuidgen -1 >> etc/products/$(NAME).csv; done
